name: Bug Feedback
description: 'Create a bug feedback to help us improve Pojav Zenith Horizon.'
title: "[BUG] Brief Description"
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Problem Description
      description: |
        Clearly and thoroughly describe the issue you encountered.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Logs/Screenshots or Videos
      description: |
        Upload logs/screenshots or videos from the most recent occurrence of this issue.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: |
        Steps to reproduce the issue. Please be as detailed as possible to help us quickly locate the problem.
      placeholder: |
        1. Open the launcher
        ... *(Steps to reproduce the issue)*
      render: markdown
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: |
        Briefly describe what you expected to happen.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Android Version
      options:
        - '14'
        - '13'
        - '12'
        - '11'
        - '10'
        - '9'
        - '8'
        - '7-'
    validations:
      required: true

  - type: input
    attributes:
      label: Pojav Zenith Horizon Version
      description: |
        What version of Pojav Zenith Horizon did you encounter this issue on? You can find this on the "About Pojav Zenith Horizon" page.
      placeholder: 1.2.3
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Information
      description: |
        Provide more information to help us reproduce and fix the issue.
      value: |
        - Device Model:
        - CPU Architecture:
      render: markdown
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: This issue has not been reported by anyone else yet
      options:
        - label: I have checked the issues and have not found any similar reports
          required: true
