name: 功能建议
description: '如果你有一些新的点子，请通过此模板告诉我们哦！'
title: "[建议] 简短的被描述"
labels: [建议]
body:
  - type: textarea
    id: version
    attributes:
      label: 功能描述
      description: |
        请在这里详细地描述出你的好点子
    validations:
      required: true

  - type: textarea
    attributes:
      label: 其他信息
      description: |
        如果可以的话，你也可以提供图片，帮助我们更好的理解你的好想法
    validations:
      required: false
