name: Feature Suggestion
description: 'If you have some new ideas, please use this template to let us know!'
title: "[Suggestion] Brief Description"
labels: [suggestion]
body:
  - type: textarea
    attributes:
      label: Feature Description
      description: |
        Please describe your great idea in detail here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Information
      description: |
        If possible, you can also provide images to help us better understand your idea.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: No one else has suggested this feature yet
      options:
        - label: I have checked the issues and have not found any similar feature suggestions
          required: true
