name: 翻译问题反馈
description: '如果你认为启动器内包含翻译不准确的文本，请通过此模板告诉我们！'
title: "[翻译问题] 简单的标题"
labels: [翻译问题]
body:
  - type: textarea
    id: version
    attributes:
      label: 哪些文本是翻译不准确的呢？
      description: |
        请在这里提供你认为翻译不准确的文本，以及你认为正确的翻译文本
      placeholder: |
        1. aaa -> bbb
        2. ccc -> ddd
      render: markdown
    validations:
      required: true

  - type: textarea
    attributes:
      label: 截图或视频
      description: |
        你需要提供应用内相关截图或视频，以方便我们更好的确定翻译不准确的文本在哪个位置
    validations:
      required: true
