name: Android CI
on:
  pull_request:
    branches-ignore:
      - ''
  push:
    branches-ignore:
      - ''
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      MOVTERY_KEYSTORE_PASSWORD: ${{ secrets.MOVTERY_KEYSTORE_PASSWORD }}

    steps:
      - name: Set IS_MAIN_BRANCH if on v3_openjdk branch
        if: github.ref_name == 'v3_openjdk'
        run: echo "IS_MAIN_BRANCH=true" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get JRE 8
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          path: app_pojavlauncher/src/main/assets/components/jre
          workflow_conclusion: success
          repo: Vera-Firefly/android-openjdk-build
          branch: buildjre8
          name: jre8-pojav

      - name: Get JRE17
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          path: app_pojavlauncher/src/main/assets/components/jre-new
          workflow_conclusion: success

          repo: Vera-Firefly/android-openjdk-build
          branch: buildjre17
          name: jre17-pojav

      - name: Get LWJGL3
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          path: app_pojavlauncher/src/main/assets/components/lwjgl3
          workflow_conclusion: success
          repo: Vera-Firefly/lwjgl3-build
          branch: official
          name: lwjgl

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6.1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Release.apk
        if: github.repository_owner == 'HopiHopy' && github.ref_name == 'v3_openjdk'
        run: |
          gradle :app_pojavlauncher:assemblerelease

      - name: Build Debug.apk
        run: |
          # Build the launcher
          gradle :app_pojavlauncher:assembleDebug

      - name: Upload Release
        continue-on-error: true
        if: github.repository_owner == 'HopiHopy' && github.ref_name == 'v3_openjdk'
        uses: actions/upload-artifact@v3
        with:
          name: PojavZH(Release)
          path: app_pojavlauncher/build/outputs/apk/release/*

      - name: Upload Debug
        uses: actions/upload-artifact@v3
        with:
          name: PojavZH(Debug)
          path: app_pojavlauncher/build/outputs/apk/debug/*

  buildnoruntime:
    runs-on: ubuntu-22.04
    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      MOVTERY_KEYSTORE_PASSWORD: ${{ secrets.MOVTERY_KEYSTORE_PASSWORD }}

    steps:
      - name: Set IS_MAIN_BRANCH if on v3_openjdk branch
        if: github.ref_name == 'v3_openjdk'
        run: echo "IS_MAIN_BRANCH=true" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3
      - name: Get LWJGL3
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          path: app_pojavlauncher/src/main/assets/components/lwjgl3
          workflow_conclusion: success
          repo: Vera-Firefly/lwjgl3-build
          branch: official
          name: lwjgl

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6.1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Release-noruntime.apk
        if: github.repository_owner == 'HopiHopy' && github.ref_name == 'v3_openjdk'
        run: |
          gradle :app_pojavlauncher:assemblerelease

      - name: Build Debug-noruntime.apk
        run: |
          # Build the launcher
          gradle :app_pojavlauncher:assembleDebug

      - name: Upload Release
        continue-on-error: true
        if: github.repository_owner == 'HopiHopy' && github.ref_name == 'v3_openjdk'
        uses: actions/upload-artifact@v3
        with:
          name: PojavZH(Release-无Java运行环境)
          path: app_pojavlauncher/build/outputs/apk/release/*

      - name: Upload Debug
        uses: actions/upload-artifact@v3
        with:
          name: PojavZH(Debug-无Java运行环境)
          path: app_pojavlauncher/build/outputs/apk/debug/*
