name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [ "all", "arm", "arm64", "x86", "x86_64" ]
      fail-fast: false
    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      MOVTERY_KEYSTORE_PASSWORD: ${{ secrets.MOVTERY_KEYSTORE_PASSWORD }}

    steps:
      - name: Set IS_MAIN_BRANCH if on main branch
        if: github.ref_name == 'main'
        run: echo "IS_MAIN_BRANCH=true" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get JRE 8
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          path: app_pojav_zh/src/main/assets/components/jre-8
          workflow_conclusion: success
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre8
          name: jre8-pojav

      - name: Get JRE 17
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          path: app_pojav_zh/src/main/assets/components/jre-17
          workflow_conclusion: success
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre17-21
          name: jre17-pojav

      - name: Get JRE 21
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          path: app_pojav_zh/src/main/assets/components/jre-21
          workflow_conclusion: success
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre17-21
          name: jre21-pojav

      - name: Get LWJGL3
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: main.yml
          path: app_pojav_zh/src/main/assets/components/lwjgl3
          workflow_conclusion: success
          repo: Vera-Firefly/lwjgl3-build
          branch: main
          name: lwjgl

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Release.apk
        if: github.repository_owner == 'HopiHopy' && github.ref_name == 'main'
        run: |
          chmod +x gradlew
          ./gradlew app_pojav_zh:assemblerelease -Darch=${{matrix.arch}}

      - name: Build Debug.apk
        run: |
          chmod +x gradlew
          ./gradlew app_pojav_zh:assembleDebug -Darch=${{matrix.arch}}

      - name: Upload Release
        continue-on-error: true
        if: github.repository_owner == 'HopiHopy' && github.ref_name == 'main'
        uses: actions/upload-artifact@v4
        with:
          name: PojavZenithHorizon(Release)-${{matrix.arch}}
          path: app_pojav_zh/build/outputs/apk/release/*

      - name: Upload Debug
        uses: actions/upload-artifact@v4
        with:
          name: PojavZenithHorizon(Debug)-${{matrix.arch}}
          path: app_pojav_zh/build/outputs/apk/debug/*

  build-noruntime:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ "all", "arm", "arm64", "x86", "x86_64" ]
      fail-fast: false
    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      MOVTERY_KEYSTORE_PASSWORD: ${{ secrets.MOVTERY_KEYSTORE_PASSWORD }}

    steps:
      - name: Set IS_MAIN_BRANCH if on main branch
        if: github.ref_name == 'main'
        run: echo "IS_MAIN_BRANCH=true" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get LWJGL3
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: main.yml
          path: app_pojav_zh/src/main/assets/components/lwjgl3
          workflow_conclusion: success
          repo: Vera-Firefly/lwjgl3-build
          branch: main
          name: lwjgl

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Debug-noruntime.apk
        run: |
          chmod +x gradlew
          ./gradlew app_pojav_zh:assembleDebug -Darch=${{matrix.arch}}

      - name: Upload Debug
        uses: actions/upload-artifact@v4
        with:
          name: PojavZenithHorizon(Debug - No Runtime)-${{matrix.arch}}
          path: app_pojav_zh/build/outputs/apk/debug/*
